[module_zzzerouid]
# モジュールの設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
resource_cdn = "https://file.minigg.cn/sayu-bot/ZZZeroUID" # {I18N:config.comments.module_zzzerouid.resource_cdn}
