[module_zzz]
# モジュールの設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
sched_energy_push = true # {I18N:config.comments.module_zzz.sched_energy_push}
widget_resin = true # {I18N:config.comments.module_zzz.widget_resin}
crazy_notice = false # {I18N:config.comments.module_zzz.crazy_notice}
refresh_bg = "bg2" # {I18N:config.comments.module_zzz.refresh_bg}
zzz_guide_provide = "猫冬" # {I18N:config.comments.module_zzz.zzz_guide_provide}
refresh_card_use_pic = true # {I18N:config.comments.module_zzz.refresh_card_use_pic}
enable_custom_char_bg = false # {I18N:config.comments.module_zzz.enable_custom_char_bg}
refresh_data_list = ["ENKA", "MINIGG", "MYS"] # {I18N:config.comments.module_zzz.refresh_data_list}
