# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字である必要があります。

[module_zzz]
# モジュールの設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
sched_energy_push = true
widget_resin = true
crazy_notice = false
refresh_bg = "bg2"
zzz_guide_provide = "猫冬"
refresh_card_use_pic = true
enable_custom_char_bg = false
refresh_data_list = ["ENKA", "MINIGG", "MYS"]
