# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。請不要在此處使用 Python 語法。
# 例如：TOML 中的布林值必須是小寫。

[module_zzz]
# 模組的組態部分，此處填寫的值可在訊息中以明文顯示。請不要在此部分填寫敏感資訊。
sched_energy_push = true
widget_resin = true
crazy_notice = false
refresh_bg = "bg2"
zzz_guide_provide = "猫冬"
refresh_card_use_pic = true
enable_custom_char_bg = false
refresh_data_list = ["ENKA", "MINIGG", "MYS"]
