# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[module_zzz]
# The basic config section of the module. The values entered here can be displayed in the message. Please do not enter sensitive information in this section.
sched_energy_push = true
widget_resin = true
crazy_notice = false
refresh_bg = "bg2"
zzz_guide_provide = "猫冬"
refresh_card_use_pic = true
enable_custom_char_bg = false
refresh_data_list = ["ENKA", "MINIGG", "MYS"]
