# https://toml.io/ko/v1.0.0
# 주의: TOML은 Python이 아닙니다. Python 문법을 사용하지 마십시오.
# 예: TOML의 불리언 값은 반드시 소문자로 작성해야 합니다.

[module_zzz]
# 모듈의 구성 섹션입니다. 여기에 입력한 값은 메시지에 일반 텍스트로 표시됩니다. 민감한 정보는 이 섹션에 입력하지 마십시오.
sched_energy_push = true
widget_resin = true
crazy_notice = false
refresh_bg = "bg2"
zzz_guide_provide = "猫冬"
refresh_card_use_pic = true
enable_custom_char_bg = false
refresh_data_list = ["ENKA", "MINIGG", "MYS"]
